website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func

class User(db.Model, UserMixin): 
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    first_name = db.Column(db.String(100))
    role = db.Column(db.String(20))

class Book(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100))
    authorname = db.Column(db.String(100))
    
class CheckedBook(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    book_id = db.Column(db.Integer, db.ForeignKey('book.id'))
    timestamp = db.Column(db.DateTime, default=func.now())

    user = db.relationship('User', backref=db.backref('checked_books', lazy=True))
    book = db.relationship('Book', backref=db.backref('checked_books', lazy=True))

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'Eldritch' ##random string key
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    from .views import views
    from .auth import auth
    
    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User
    
    with app.app_context():
        db.create_all()
        
        
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app

def create_database(app):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=app)
        print('Created Database')

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in Successfully', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect Password, try again', category='error')
        else:
            flash('Email does not exist', category='error')
        
    return render_template("login.html")

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST' :
        email = request.form.get('email')
        firstName = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        role = request.form.get('role')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists', category='error')

        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')

        elif len(firstName) < 2:
            flash('First name must be greater than 1 characters.', category='error')

        elif password1!= password2:
            flash('Passwords do not match.', category='error')

        elif len(password1) < 7:
            flash('Password must be at least 7 characters.', category='error')

        elif role not in ['general', 'admin', 'librarian']:
            flash('Invalid role', category='error')

        elif user is None: 

            #add user to database
            new_user = User(email=email, first_name=firstName, password=generate_password_hash(password1, method='pbkdf2:sha256'), role=role)
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created', category='success')
            return redirect(url_for('views.home'))
    return render_template("signup.html", user=current_user)

website/views.py
from flask import Blueprint, redirect, render_template, request, flash, jsonify, url_for
from flask_login import login_required, current_user

from .models import Book, CheckedBook, User
from . import db
import json

views = Blueprint('views', __name__)

#home page
@views.route("/")
def home():
    return render_template("home.html")

#browse book age
@views.route("/browse")
def browse():
    books = Book.query.all()
    return render_template("browse.html", books=books)

@views.route("/select_book/<int:book_id>")
@login_required
def select_book(book_id):
    book = Book.query.get_or_404(book_id)
    if CheckedBook.query.filter_by(user_id=current_user.id, book_id=book_id).first():
        flash('You already have this book selected', category='error')
    else:
        checked_book = CheckedBook(user_id=current_user.id, book_id=book_id)
        db.session.add(checked_book)
        db.session.commit()
        flash('Book selected', category='success')
    return redirect(url_for('views.browse'))

#logout page
@views.route("/logout")
def logout():
    return redirect(url_for("views.home"))

#add / remove book page
@views.route("/bookBase", methods=['GET', 'POST'])
def bookBase():
    if request.method == 'POST':
        title = request.form.get('title')
        author = request.form.get('author')

        book = Book.query.filter_by(title=title).first()
        if book:
            flash('Already have copy of book', category='error')
        else:
            #add book to database
            new_book = Book(title=title, authorname=author)
            db.session.add(new_book)
            db.session.commit()
            flash('Book added', category='success')
        
    books = Book.query.all()
    return render_template("bookBase.html", books=books)

#delete book
@views.route("/delete_book/<int:book_id>", methods=['GET', 'POST'])
@login_required
def delete_book(book_id):
    book = Book.query.get_or_404(book_id)
    db.session.delete(book)
    db.session.commit()
    flash('Book deleted', category='success')
    return redirect(url_for('views.bookBase'))

#add / remove account page
@views.route("/userBase")
@login_required
def userBase():
    users = User.query.all()
    return render_template("userBase.html", users=users)

#delete user
@views.route("/delete_user/<int:user_id>", methods=['GET', 'POST'])
@login_required
def delete_user(user_id):
    user = User.query.get_or_404(user_id)
    if user.id == current_user.id:
        flash('You cannot delete yourself', category='error')
        return redirect(url_for('views.userBase'))
    db.session.delete(user)
    db.session.commit()
    flash('User deleted', category='success')
    return redirect(url_for('views.userBase'))

@views.route("/checkedBooks")
@login_required
def checkedBase():
    checked_books = CheckedBook.query.filter_by(user_id=current_user.id).all()
    return render_template("checkedBooks.html", checked_books=checked_books)

@views.route("/remove_checked_book/<int:book_id>", methods=['GET', 'POST'])
@login_required
def remove_checked_book(book_id):
    checked_book = CheckedBook.query.filter_by(user_id=current_user.id, book_id=book_id).first()
    if checked_book:
        db.session.delete(checked_book)
        db.session.commit()
        flash('Book removed from checked books', category='success')
    else:
        flash('Book not found in checked books', category='error')
    return redirect(url_for('views.checkedBase'))

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="browse" href="/browse">Browse</a>
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signup" href="/signup">SignUp</a>
          {% if current_user.is_authenticated %}
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          <a class="nav-item nav-link" id="checkedBooks" href="/checkedBooks">Selected Books</a>
          {% endif %}
          {% if current_user.role in ['librarian', 'admin'] %}
          <a class="nav-item nav-link" id="bookBase" href="/bookBase">Book Database</a>
          {% endif %}
          {% if current_user.role == 'admin' %}
          <a class="nav-item nav-link" id="userBase" href="/userBase">User Database</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

website/templates/bookBase.html
{% extends "base.html" %} {% block content %}
<form method="POST">
  <h3 align="center">Add Book</h3>
  <label for="title">Title:</label>
  <input type="text" id="title" name="title" required />
  <br />
  <label for="author">Author:</label>
  <input type="text" id="author" name="author" required />
  <br />
  <input type="submit" value="Add Book" />
</form>

<h3 align="center">Book List</h3>
<div style="overflow-y: scroll; height: 300px">
  <ul>
    {% for book in books %}
    <li>
      {{ book.title }} by {{ book.authorname }}
      <a href="{{ url_for('views.delete_book', book_id=book.id) }}">&times;</a>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

website/templates/browse.html
{% extends "base.html" %} {% block content %}
<h1>Browse</h1>
<ul>
  {% for book in books %}
  <li>
    {{ book.title }} by {{ book.authorname }}
    <a href="{{url_for('views.select_book', book_id=book.id)}}">Select</a>
  </li>
  {% endfor %}
</ul>
{% endblock %}

website/templates/checkedBooks.html
{% extends "base.html" %} {% block content %}
<h1>Selected Books</h1>
<ul>
  {% for checked_book in checked_books %}
  <li>
    {{ checked_book.book.title }} by {{ checked_book.book.authorname }}
    <a
      href="{{ url_for('views.remove_checked_book', book_id=checked_book.book_id) }}"
      >Remove</a
    >
  </li>
  {% endfor %}
</ul>
{% endblock %}

website/templates/checkout.html
{% extends "base.html" %} {% block content %}
<h1>Checked Out Books</h1>
<ul>
  {% for checked_book in checked_books %}
  <li>{{ checked_book.book.title }} by {{ checked_book.book.authorname }}</li>
  {% endfor %}
</ul>
{% endblock %}

website/templates/home.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block content
%}
<h1>Front Page, Mostly Blank Because 
    I mostly used the Nav Bar</h1>
{% endblock %}

website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %}
{%block content %}
<form method="POST">
    <h3 align="center">Login</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password"
        name="password" 
        placeholder="Enter password"
      />
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Login</button>
  </form>
{%endblock%}

website/templates/signup.html
{% extends "base.html" %} {% block title %}SignUp{% endblock %} {%block content
  %}
  <form method="POST">
    <h3 align="center">Sign Up</h3>
    <div class="form-group">
      <label for="email">Email Address</label>
      <input
        type="email"
        class="form-control"
        id="email"
        name="email"
        placeholder="Enter email"
      />
    </div>
    <div class="form-group">
      <label for="firstName">First Name</label>
      <input
        type="text"
        class="form-control"
        id="firstName"
        name="firstName" 
        placeholder="Enter first name"
      />
    </div>
    <div class="form-group">
      <label for="password1">Password</label>
      <input
        type="password"
        class="form-control"
        id="password1"
        name="password1" 
        placeholder="Enter password"
      />
    </div>
    <div class="form-group">
      <label for="password2">Password (Confirm)</label>
      <input
        type="password"
        class="form-control"
        id="password2"
        name="password2" 
        placeholder="Confirm"
      />
    </div>
    <div class="form-group">
      <label for="role">Role</label>
      <select class="form-control" id="role" name="role">
        <option value="general">General</option>
        <option value="admin">Admin</option>
        <option value="librarian">Librarian</option>
      </select>
    </div>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  {%endblock%}

website/templates/userBase.html
{% extends "base.html" %}

{% block content %}
  <h3 align="center">Users</h3>
  <div style="overflow-y: scroll; height: 300px;">
    <ul>
      {% for user in users %}
        <li>{{ user.first_name }} <a href="{{ url_for('views.delete_user', user_id=user.id) }}">Delete</a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock %}